### ISSUE TITLE
Doesn't work, shipping broken

### ISSUE THREAD

**Issue by s1nistr4** [rest-nvim/rest.nvim#186] opened 2023-02-28 01:00 UTC
I am copying and pasting from the readme file and it doesn't work. None of the commands documented are available.

**Comment by JulesNP** [comment] 2023-04-15 14:27
Unfortunately this plugin doesn't create any vim commands, only `<Plug>` mappings, so to use it you need to make keymaps, for example:
```vim
nnoremap <leader>rr <Plug>RestNvim
nnoremap <leader>rl <Plug>RestNvimLast
nnoremap <leader>rp <Plug>RestNvimPreview
```

**Comment by NTBBloodbath** [comment] 2023-04-15 14:37
This is the intended behavior at the time of closing this issue. This is going to change on next release where rest.nvim will expose a `:Rest` command.

**Closed** 2023-04-15 14:36 UTC
