### ISSUE TITLE
use `content-type:`, other casing doesn't work

### ISSUE THREAD

**Issue by xbladesub** [rest-nvim/rest.nvim#157] opened 2022-12-02 11:46 UTC
I used rest.nvim couple of weeks ago and everything was fine. However it doesn't work anymore and I have no idea why. 

This is my request:
```
POST http://127.0.0.1:8080/v1/user/signup
Content-Type: application/json
API-TOKEN: API-TOKEN: 0a479179624fb5255cb9054603382077dd7366b0319386dd89b12806463bd000

{
  "device_id": "admin_1",
  "password": "admin_1"
}
```

I use Rust - actix-web framework. It says ```Error in response: Deserialize(Error("expected value", line: 1, column: 1))```

Btw, everything is okay in Insomnia and Postman

**Comment by jungai** [comment] 2022-12-03 16:07
Same issue, maybe because of this

```bash
curl -sSL --compressed -X 'POST' -H 'Content-Type:  application/json' -d 'key=value' -d 'key=value' -d 'key=value' 'url'
```

**Comment by Emptyfruit** [comment] 2022-12-04 13:02
Can be related to https://github.com/rest-nvim/rest.nvim/issues/114 because I got this issue after installing today for the first time.

**Comment by sjdonado** [comment] 2022-12-06 19:20
Same here. This project seems to be a bit abandoned :(

**Comment by rhinoxi** [comment] 2022-12-08 07:12
I think this is related to the PR https://github.com/rest-nvim/rest.nvim/pull/142 in this thread https://github.com/rest-nvim/rest.nvim/issues/141#issuecomment-1330348198, which makes "Content-Type: application/json" couldn't be recognized and the brace around the raw body will be removed when calling curl.

**Comment by MikaelElkiaer** [comment] 2022-12-19 07:36
> Same here. This project seems to be a bit abandoned :(

It does seem abandoned.

If you see the branch [document-competition](https://github.com/rest-nvim/rest.nvim/tree/document-competition#related-software) there is an alternative [Hurl](https://github.com/Orange-OpenSource/hurl) that seems a lot more mature, although it is not specifically for Neovim.
There is also a [tree-sitter grammar](https://github.com/otherJL0/tree-sitter-hurl) and you could probably use something like [flow.nvim](https://github.com/arjunmahishi/flow.nvim) to execute - combining the two and you could do a visual via tree-sitter and run with flow.

**Comment by sharksforarms** [comment] 2022-12-20 18:37
for those looking for a quick work-around, replace `Content-Type` with `content-type`

**Comment by teto** [comment] 2022-12-20 22:51
> If you see the branch [document-competition](https://github.com/rest-nvim/rest.nvim/tree/document-competition?rgh-link-date=2022-12-19T07%3A36%3A23Z#related-software)

That branch got merged hence the "competition" appears at https://github.com/rest-nvim/rest.nvim#related-software .
I am trying to add testing to prevent this kind of regression but any help welcome ofc

**Comment by MikaelElkiaer** [comment] 2022-12-21 06:49
> > If you see the branch [document-competition](https://github.com/rest-nvim/rest.nvim/tree/document-competition?rgh-link-date=2022-12-19T07%3A36%3A23Z#related-software)
> 
> That branch got merged hence the "competition" appears at https://github.com/rest-nvim/rest.nvim#related-software . I am trying to add testing to prevent this kind of regression but any help welcome ofc

Did you consider utilizing Hurl as a request engine, instead of the current one?
This would offer a lot more, and possibly more stable, features - and still get the benefits of the Neovim integration.

**Comment by rochacbruno** [comment] 2022-12-23 18:22
> for those looking for a quick work-around, replace `Content-Type` with `content-type`

This is what works for me!

**Comment by teto** [comment] 2022-12-28 22:24
> Did you consider utilizing Hurl as a request engine, instead of the current one?

I am testing hurl at the moment but note that I am not the creator of the plugin. I just added 2/3 commits to fix issues as I use this plugin in my work. I prefer to keep the work to a minimum though I would be curious to experiment with teal for this plugin. 

> This would offer a lot more, and possibly more stable, features - and still get the benefits of the Neovim integration.

The benefits of neovim integration is to be able to run inline lua code as done https://github.com/rest-nvim/rest.nvim/pull/122. Not something that hurl can do. I would be curious in your feedback running hurl-based request with [flow.nvim](https://github.com/arjunmahishi/flow.nvim). For me the real issue is the absence of testing, once this is fixed (and I've done mmuch progress if you look at main in that regard), we should be much better off. This issue is my current priority.

**Comment by rochacbruno** [comment] 2022-12-29 15:29
I was thinking about a hurl plugin for neovim but I don´t like the fact that hurl runs the whole file and I want to be able to have a single  `.http` file for a feature/project and run each request individually.

Also, hurl introduces too much syntax that is not exactly pure HTTP, the best thing in rest-nvim is that it is a pure http request format.

**Closed** 2022-12-30 17:41 UTC

**Comment by teto** [comment] 2023-05-11 13:32
@rochacbruno I haven't upgraded my fork of https://github.com/rest-nvim/rest.nvim/pull/174 in a long time. Right now I am testing hurl. I've opened  https://github.com/rest-nvim/rest.nvim/issues/195 in case you are interested
