### ISSUE TITLE
Can we have multiple luarocks installations?

### ISSUE THREAD

**Issue by mesa123123** [rest-nvim/rest.nvim#332] opened 2024-03-22 21:42 UTC
There are multiple ways of installing luarocks through nvim and 

https://github.com/camspiers/luarocks

might be able to be a drop in replacement?
Could we possibly modify the code to use that instead?

**Comment by NTBBloodbath** [comment] 2024-03-22 22:32
Possible duplicate of #331, please see [my comment](https://github.com/rest-nvim/rest.nvim/issues/331#issuecomment-2016028668) there.

**Closed by NTBBloodbath** 2024-03-22 22:32 UTC
