### ISSUE TITLE
Fails to install, says: fidget.nvim is not installed, even though it is! 

### ISSUE THREAD

**Issue by mcmoodoo** [rest-nvim/rest.nvim#497] opened 2024-11-27 08:42 UTC
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.10.2 Build type: RelWithDebInfo LuaJIT 2.1.1731601260

### Operating system/version

Archlinux x86_64 Kernel 6.12.1-arch1-1

### Actual behavior

after adding the follwing into the config.lua:

lvim.plugins = {
  {"nvim-neotest/nvim-nio"},
  {"j-hui/fidget.nvim"},
  {"manoelcampos/xml2lua"},
  {"rest-nvim/rest.nvim"},
}

I GET THE ERROR after installing and reloading nvim:

vim/_editor.lua:0: /home/mcmoodoo/.local/share/lunarvim/lvim/init.lua..nvim_exec2() called at /home/mcmoodoo/.local/share/lunarvim/lvim/init.lua:0../home/mcmoodoo/.local/share/lunarvim/site/pack/lazy/opt/rest.nvim/plugin/rest-nvim.lua: Vim(source):WARN: Dependency 'fidget.nvim' was not found. rest.nvim will be completely unable to show request progress messages

it alternates between complaining that one of these is missing:
- fidget.nvim
- xml2lua
- mimetypes

### Expected behavior

Well, I expect the thing to at least run :)

### Steps to reproduce

add the above into the ~/.config/lvim/config.lua and reload lvim

### Repro (`lazy.nvim`)

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
    spec = {
        "rest-nvim/rest.nvim",
        {
            "nvim-treesitter/nvim-treesitter",
            build = ":TSUpdate",
            main = "nvim-treesitter.configs",
            opts = {
                ensure_installed = { "http" },
                sync_install = false,
                highlight = { enable = true },
                indent = { enable = true },
            },
        },
    },
})
```

**Comment by boltlessengineer** [comment] 2024-12-07 11:00
duplicate of #493

Seems like you are using LunarVim.
LunarVim is using legacy `lazy.nvim` version which doesn't support dependency installation through luarocks & rockspec.
You can only install this plugin through plugin managers supporting luarocks such as latest `lazy.nvim` or `rocks.nvim`

**Closed by boltlessengineer** 2024-12-07 11:00 UTC
Labels: bug
