### ISSUE TITLE
[Bug] Can't recognize the variable in header

### ISSUE THREAD

**Issue by Alienover** [rest-nvim/rest.nvim#378] opened 2024-05-03 17:50 UTC
<img width="1879" alt="image" src="https://github.com/rest-nvim/tree-sitter-http/assets/12182069/399e62de-f5bc-448c-bd7e-e8847bdefb66">

The `{{TOKEN}}` in this case, is parsed as `value`, instead of `variable`.

The header should be parsed to 
```
  header
    name: name
    value: value
    value: value
    value: variable
      name: identifier
```

**Comment by malisoft** [comment] 2024-05-08 00:04
Same problem, in my case, i tried 
![image](https://github.com/rest-nvim/rest.nvim/assets/55772887/999d7c69-4a9f-447f-93be-283c831d0401)
i old versions works, but i still i love this package, only is solve this little problem

**Comment by malisoft** [comment] 2024-05-08 01:22
> Same problem, in my case, i tried ![image](https://private-user-images.githubusercontent.com/55772887/328712734-999d7c69-4a9f-447f-93be-283c831d0401.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMzEyMzksIm5iZiI6MTcxNTEzMDkzOSwicGF0aCI6Ii81NTc3Mjg4Ny8zMjg3MTI3MzQtOTk5ZDdjNjktNGE5Zi00NDdmLTkzYmUtMjgzYzgzMWQwNDAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDAxMTUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmMDJjMDc4YzhmNjMxMzkwMTYxMWIyYTZmMzZmOTYxMmMxMjFkZmM1ZTUyYmYyMTEwZGMxMzJlMTJlMTdlNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WJk5546eMfG90izzXlX0qFbH47sZTxb0aiS-pVWaOA8) in older versions works, but i still i love this package, only is solve this little problem

i find a solution, the problem iss because by some reason does not work when is together "Bearer {{TOKEN}}" i created another env file called ".env.http" selecting this env file using the Telescope rest env selector and storing in this env file:

```bash
TOKEN=Bearer ey.......
```

note that i am using a variable with a content without spaces between the texts(the problem was laravels does not support spaces un the env variables as well) 

Finally this works:
```http
GET {{APP_URL}}/api/1.0/apps?per_page=15
Authorization: {{TOKEN}}
Content-Type:application/json
```

**Comment by Alienover** [comment] 2024-05-08 15:57
@malisoft that's the solution I am using.... have to replace the whole `Authorization` value.

**Comment by NTBBloodbath** [comment] 2024-05-08 17:10
Hi, sorry for the delay. Life has been kinda busy and I'm still during exams weeks :/

I'm going to move this issue to the `tree-sitter-http` repository, as it seems to be a problem with the parser and not with rest.nvim itself and fix it as soon as I have some spare time to work on it.

**Comment by Alienover** [comment] 2024-05-08 17:15
https://github.com/rest-nvim/tree-sitter-http/issues/29 
I created this issue in `tree-sitter-http` before. No one replied, so I duplicated it here for visibility.

**Comment by javoscript** [comment] 2024-05-31 13:25
I was having issues with setting the `Authentication: Bearer XXXXX` header, and it ended up being a problem when three conditions happen at the same time:

- the value contains a space (between `Bearer` and the actual token, for example)
- the token contains a pipe character "`|`"
- the header value (concatenating the `Bearer` part and the token) was being made in the request definition

Whenever all happen, setting the header like this won't work:

```
GET /api/test
host: {{API_BASE_URL}}
Accept: application/json
Authorization: Bearer {{BEARER_TOKEN}}
```

The value received by the server is just `Authorization: Bearer`.

BUT, if the env variable already contains the whole value (with the `Bearer` part), then it works.

Here a snippet of how I'm setting the complete `Authorization` header value:

```http
POST /api/auth
host: {{API_BASE_URL}}
Content-Type: application/json

{
   "email": "email@example.com",
   "password": "secret"
}

--{%

local body = context.json_decode(context.result.body)
context.set_env("BEARER_TOKEN", "Bearer " .. body.token)

--%}
```

**Comment by boltlessengineer** [comment] 2024-08-23 16:48
This seems to be a [tree-sitter-http](https://github.com/rest-nvim/rest.nvim) issue.
Closing this due to v3 release.

**Closed by boltlessengineer** 2024-08-23 16:48 UTC
