### ISSUE TITLE
Host or host?

### ISSUE THREAD

**Issue by ray-x** [rest-nvim/rest.nvim#163] opened 2022-12-29 03:49 UTC
In sample:
```rest
GET /api/users?page=5 HTTP/1.1
Host: reqres.in:443
```
But in code it check `host`:

https://github.com/rest-nvim/rest.nvim/blob/c5094a8ae90e3d2411f4de988c379c863593f0e0/lua/rest-nvim/request/init.lua#L276-L281

This makes the sample not work,
Is the sample incorrect or the request/init.lua is incorrect?

**Comment by teto** [comment] 2022-12-29 13:48
closing as duplicate of https://github.com/rest-nvim/rest.nvim/issues/157 . There is an issue with casing of the headers at the moment. I think we need to generate a normalized version of the headers but keep sending the original headers. PR welcome

**Comment by teto** [comment] 2022-12-30 17:44
we merged a fix for content-type but not for that one so reopening

**Closed** 2023-10-10 18:40 UTC
