### ISSUE TITLE
Wrong regtype for `getregionpos`

### ISSUE THREAD

**Issue by tochamateusz** [rest-nvim/rest.nvim#387] opened 2024-05-26 09:17 UTC
I had a problem with `Rest run cursor` 

```lua
Error executing Lua callback: Vim:E475: Invalid value for argument type: c
stack traceback:
        [C]: in function 'getregionpos'
        ..._lvimoUopG3/usr/share/nvim/runtime/lua/vim/highlight.lua:72: in function 'range'
        ...vim/site/pack/lazy/opt/rest.nvim/lua/rest-nvim/utils.lua:136: in function 'highlight'
        ...site/pack/lazy/opt/rest.nvim/lua/rest-nvim/functions.lua:66: in function 'exec'
        .../site/pack/lazy/opt/rest.nvim/lua/rest-nvim/commands.lua:44: in function 'impl'
        .../site/pack/lazy/opt/rest.nvim/lua/rest-nvim/commands.lua:182: in function <.../site/pack/lazy/opt/rest.nvim/lua/rest-nvim/commands
.lua:165>
```

```bash
❯ lvim --version
NVIM v0.11.0-dev-98+g3d39ea3ea
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

According `_meta/vimfn.lua` 

```lua
--- The result is a String, which is type of register {regname}.
--- The value will be one of:
---     "v"      for |charwise| text
---     "V"      for |linewise| text
---     "<CTRL-V>{width}"  for |blockwise-visual| text
---     ""      for an empty or unknown register
--- <CTRL-V> is one character with value 0x16.
```

so I change 

```lua
  vim.highlight.range(
    bufnr,
    ns,
    higroup,
    { start, 0 },
    { end_, string.len(vim.fn.getline(end_)) },
    { regtype = "c", inclusive = false }
  )
``` 
to

```lua
  vim.highlight.range(
    bufnr,
    ns,
    higroup,
    { start, 0 },
    { end_, string.len(vim.fn.getline(end_)) },
    { regtype = "v", inclusive = false }
  )
```

and error seems to be gone. 

But in this case I have problem with request like this:
```bash
POST http://localhost:8081/login-by-email
Authorization: Bearer <some-token>
Content-Type: application/json

{
  "email": "email",
  "password": "password"
}
```
and I am getting

```lua
# [rest.nvim] ERROR: The tree-sitter node at the range [0:0 - 8:0] has a syntax error and cannot be parsed
# Error executing Lua callback: ...te/pack/lazy/opt/rest.nvim/lua/rest-nvim/parser/init.lua:143: attempt to index local 'document_node' (a nil value)
# stack traceback:
#         ...te/pack/lazy/opt/rest.nvim/lua/rest-nvim/parser/init.lua:143: in function 'traverse_variables'
#         ...te/pack/lazy/opt/rest.nvim/lua/rest-nvim/parser/init.lua:434: in function 'parse'
#         ...site/pack/lazy/opt/rest.nvim/lua/rest-nvim/functions.lua:61: in function 'exec'
#         .../site/pack/lazy/opt/rest.nvim/lua/rest-nvim/commands.lua:44: in function 'impl'
#         .../site/pack/lazy/opt/rest.nvim/lua/rest-nvim/commands.lua:182: in function <.../site/pack/lazy/opt/rest.nvim/lua/rest-nvim/commands.lua:165>
# Press ENTER or type command to continue
```

**Comment by boltlessengineer** [comment] 2024-05-26 19:00
I can reproduce this from nvim v0.11.0, v0.10.0 is fine though.

**Comment by NTBBloodbath** [comment] 2024-05-27 04:39
Hi there, currently `rest.nvim` only target stable Neovim releases so I'm not willing to fix it myself. If the changed behavior works as expected there and also in `>= 0.9.2` then a PR is welcome :)

Ps: the last error is kinda expected sadly. We have yet to implement the `Authorization: Foo Bar` in the [tree-sitter-http](https://github.com/rest-nvim/tree-sitter-http) parser and my free time is very limited right now :(

**Comment by tochamateusz** [comment] 2024-05-27 20:31
Is not already implemented?
I saw some test 
[https://github.com/rest-nvim/tree-sitter-http/blob/8d22f33faa5aa95c6526606fb656ada342e59e40/test/corpus/body.txt#L105](https://github.com/rest-nvim/tree-sitter-http/blob/8d22f33faa5aa95c6526606fb656ada342e59e40/test/corpus/body.txt#L105)

And they are using `Authorization` header

**Comment by boltlessengineer** [comment] 2024-08-22 05:21
Closing this due to v3 release. Now both regtype issue and bearer token variable should be fixed.

**Closed by boltlessengineer** 2024-08-22 05:21 UTC
