### ISSUE TITLE
Getting response json in 1 line

### ISSUE THREAD

**Issue by xbladesub** [rest-nvim/rest.nvim#248] opened 2023-11-10 01:52 UTC
I receive response json in 1 line:
<img width="913" alt="image" src="https://github.com/rest-nvim/rest.nvim/assets/45129790/370605e8-7df1-4f41-a761-a09180fe6ac8">

Is this a bug?

edit: 
I switched to commit `f13ae54ae2545d4d612593d4a442cbb33a1b5b65` and everything seems fine. I'm not sure which exact commit is buggy...

just in case - I use Neovide

**Comment by isturiz** [comment] 2023-11-17 05:51
I have the same problem. I already installed jq and tidy and it doesn't work.

**Comment by NTBBloodbath** [comment] 2023-11-17 22:13
Hey,

Yes, unfortunately it is a bug as you can see in #246 and I haven't had time to finish implementing the fix :(

I will close this issue as a duplicate of the issued one I mentioned above to avoid pollution.

**Closed** 2023-11-17 22:14 UTC
